environment:
  matrix:
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"
install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install cython"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe -m pip install -e ."
build: off
test_script:
  - "%PYTHON%\\python.exe -m pytest spacy/ --no-print-logs"
after_test:
  - "%PYTHON%\\python.exe setup.py bdist_wheel"
artifacts:
  - path: dist\*
branches:
  except:
    - spacy.io
