language: python

sudo: false
dist: trusty
group: edge

python:
   - "2.7"
   - "3.5"

os:
  - linux

env:
  - VIA="compile"
  - VIA="sdist"

install:
  - "./travis.sh"

script:
  - "pip install pytest"
  - if [[ "${VIA}" == "compile" ]]; then SPACY_DATA=models/en python -m pytest spacy; fi
  - if [[ "${VIA}" == "pypi" ]]; then python -m pytest `python -c "import pathlib; import spacy; print(pathlib.Path(spacy.__file__).parent.resolve())"`; fi
  - if [[ "${VIA}" == "sdist" ]]; then python -m pytest `python -c "import pathlib; import spacy; print(pathlib.Path(spacy.__file__).parent.resolve())"`; fi
