language: python

sudo: false
dist: trusty
group: edge

python:
   - "2.7"
   - "3.5"

os:
  - linux

env:
  - VIA="pypi"
  - VIA="compile"

install:
  - "./travis.sh"

script:
  - "pip install pytest"
  - if [[ "${VIA}" == "compile" ]]; then SPACY_DATA=models/en python -m pytest spacy; fi
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${VIA}" == "pip" ]]; then python -m pytest spacy; fi
