language: python

sudo: required
dist: trusty
group: edge

python:
   - "2.7"
   - "3.5"

os:
  - linux
  - osx

install:
  - "pip install -r requirements.txt"
  - "pip install -e ."
  - "mkdir -p corpora/en"
  - "cd corpora/en"
  - "wget --no-check-certificate http://wordnetcode.princeton.edu/3.0/WordNet-3.0.tar.gz"
  - "tar -xzf WordNet-3.0.tar.gz"
  - "mv WordNet-3.0 wordnet"
  - "cd ../../"
  - "mkdir models/"
  - "python bin/init_model.py en lang_data/ corpora/ models/en"

script:
  - "pip install pytest"
  - "SPACY_DATA=models/en python -m pytest spacy"
