language: python

os:
  - linux
  - osx

python:
  - "2.7"
  - "3.4"

# command to install dependencies
install:
  - "pip install --upgrade setuptools"
  - "pip install -r requirements.txt"
  - "export PYTHONPATH=`pwd`"
  - "python setup.py build_ext --inplace"
# command to run tests
script:
  - py.test tests/
