language: python

sudo: required
dist: precise
group: edge

python:
   - "2.7"
   - "3.4"

os:
  - linux

install:
  - pip install -r requirements.txt
  - python setup.py sdist
  - pip install dist/*

script:
  - python -m spacy.en.download
  - python -m pytest spacy/ -x --models --vectors --slow
