language: python

matrix:
  include:
  - sudo: required
    dist: precise
    group: edge
  - sudo: required
    dist: trusty

python:
   - "2.7"
   - "3.4"

os:
  - linux

install:
  - pip install -r requirements.txt

script:
  - python -m spacy.en.download
  - python -m pytest spacy/ -x --models --vectors --slow
