language: python

sudo: required
dist: precise
group: edge

python:
   - "2.7"
   - "3.4"

os:
  - linux

env:
  - PIP_DATE=2015-10-01 MODE=pip
  - PIP_DATE=2015-10-01 MODE=setup-install
  - PIP_DATE=2015-10-01 MODE=setup-develop

install:
  - pip install --disable-pip-version-check -U pip
  - python build.py prepare $PIP_DATE

script:
  - python build.py $MODE;
  - python build.py test
