language: python

os:
  - linux
  - osx

python:
  - "2.7"
  - "3.4"

# install dependencies
install:
  - "pip install --upgrade setuptools"
  - "pip install cython fabric fabtools"
  - "pip install -r requirements.txt"
  - "python setup.py build_ext --inplace"
  - "mkdir -p corpora/en"
  - "cd corpora/en"
  - "wget --no-check-certificate http://wordnetcode.princeton.edu/3.0/WordNet-3.0.tar.gz"
  - "tar -xzf WordNet-3.0.tar.gz"
  - "mv WordNet-3.0 wordnet"
  - "cd ../../"
  - "export PYTHONPATH=`pwd`"
  - "python bin/init_model.py lang_data/en corpora/en spacy/en/data"

# run tests
script:
  - py.test tests/
