language: python

sudo: required
dist: precise
group: edge

python:
   - "2.7"
   - "3.4"

os:
  - linux

env:
  - PIP_DATE=2015-01-01 PIP=1 INSTALL=0 DEVELOP=0
  - PIP_DATE=2015-04-01 PIP=1 INSTALL=0 DEVELOP=0
  - PIP_DATE=2015-07-01 PIP=1 INSTALL=0 DEVELOP=0
  - PIP_DATE=2015-10-01 PIP=1 INSTALL=0 DEVELOP=0

  - PIP_DATE=2015-01-01 PIP=0 INSTALL=1 DEVELOP=0
  - PIP_DATE=2015-04-01 PIP=0 INSTALL=1 DEVELOP=0
  - PIP_DATE=2015-07-01 PIP=0 INSTALL=1 DEVELOP=0
  - PIP_DATE=2015-10-01 PIP=0 INSTALL=1 DEVELOP=0

  - PIP_DATE=2015-01-01 PIP=0 INSTALL=0 DEVELOP=1
  - PIP_DATE=2015-04-01 PIP=0 INSTALL=0 DEVELOP=1
  - PIP_DATE=2015-07-01 PIP=0 INSTALL=0 DEVELOP=1
  - PIP_DATE=2015-10-01 PIP=0 INSTALL=0 DEVELOP=1

install:
  - pip install -U pip
  - python pip-date.py $PIP_DATE pip setuptools wheel six
  - pip install -r requirements.txt

  - if [[ "$PIP" == "1" ]]; then
      python setup.py sdist;
      pip install dist/*;
    fi

  - if [[ "$INSTALL" == "1" ]]; then
      python setup.py install;
    fi

  - if [[ "$DEVELOP" == "1" ]]; then
      python setup.py develop;
      pip install -e .;
    fi

  - pip install pytest
  - pip list

script:
  - mkdir tmp; cd tmp
  - python -m spacy.en.download
  - python -m pytest ../spacy/ -x --models --vectors --slow
