language: python

sudo: required
dist: precise
group: edge

python:
   - "2.7"
   - "3.4"

os:
  - linux

env:
  - PIP_DATE=2014-07-01
  - PIP_DATE=2014-10-01
  - PIP_DATE=2015-01-01
  - PIP_DATE=2015-04-01
  - PIP_DATE=2015-07-01
  - PIP_DATE=2015-10-01

install:
  - pip install -U pip
  - python pip-date.py $PIP_DATE pip setuptools wheel six
  - pip install -r requirements.txt
  - python setup.py sdist
  - pip install dist/*

script:
  - mkdir tmp; cd tmp
  - python -m spacy.en.download
  - python -m pytest ../spacy/ -x --models --vectors --slow
