language: python

os:
  - linux
  - osx

python:
  - "2.7"
  - "3.4"

# install dependencies
install:
  - "pip install --upgrade setuptools"
  - "rm -rf spacy/"
  - "pip install spacy"

# run tests
script:
  - py.test tests/tokenizer/
  - py.test tests/vocab/
  - py.test tests/tagger/
