language: python
python:
  - "2.7"
  - "3.4"
  - "pypy"

# command to install dependencies
install:
  - "pip install --upgrade setuptools"
  - "pip install spacy"
  - "rm -rf spacy/"
# command to run tests
script:
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then py.test tests/; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then py.test-pypy tests/; fi
