language: python

os:
  - linux
  - osx

python:
  - "2.7"
  - "3.4"

# install dependencies
install:
  - "pip install --upgrade setuptools"
  - "pip install -r requirements.txt"
  - "pip install fabric fabtools"
  - "export PYTHONPATH=`pwd`"
  - "fab make"
  - "python -m spacy.en.download all"
  - "py.test tests/"

#- "rm -rf spacy/"
#- "pip install spacy"
#- "python -m spacy.en.download all"
# run tests
script:
  - py.test tests/
