language: python

sudo: required
dist: precise
group: edge

python:
   - "2.7"
   - "3.4"

os:
  - linux

env:
  - SETUPTOOLS=19
  - SETUPTOOLS=18
  - SETUPTOOLS=17

install:
  - pip install -U pip
  - pip uninstall -y setuptools
  - pip install setuptools<$SETUPTOOLS
  - pip install -r requirements.txt
  - python setup.py sdist
  - pip install dist/*

script:
  - mkdir tmp; cd tmp
  - python -m spacy.en.download
  - python -m pytest ../spacy/ -x --models --vectors --slow
