language: python

group: edge

python:
   - "2.7"
   - "3.4"
   - "3.5"

os:
  - linux
  - osx

install:
  - pip install --user -r requirements.txt

script:
  - python -m spacy.en.download
  - python -m pytest spacy/ -x --models --vectors --slow
