language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  - "pip install --upgrade setuptools"
  - "pip install murmurhash numpy spacy"
  - "rm -rf spacy/"
# command to run tests
script: "py.test tests/"
