language: python

python:
   - "2.7"
   - "3.4"

os:
  - linux
  - osx

install:
  - pip install -r requirements.txt

script:
  - python -m spacy.en.download
  - python -m pytest spacy/ -x --models --vectors --slow
