build: off

branches:
  only:
    - master
    - develop

notifications:
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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
    channel: '#dev'
