trigger:
  batch: true
  branches:
    include:
    - '*'
    exclude:
    - 'spacy.io'
  paths:
    exclude:
    - 'website/*'
    - '*.md'
pr:
  paths:
    exclude:
    - 'website/*'
    - '*.md'

jobs:

# Perform basic checks for most important errors (syntax etc.) Uses the config
# defined in .flake8 and overwrites the selected codes.
- job: 'Validate'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
  - script: |
      pip install flake8
      python -m flake8 spacy --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    displayName: 'flake8'

- job: 'Test'
  dependsOn: 'Validate'
  strategy:
    matrix:
# Test on one OS per python 3.6/3.7/3.8/3.9 to speed up CI
      Python36Linux:
        imageName: 'ubuntu-20.04'
        python.version: '3.6'
      Python37Windows:
        imageName: 'windows-latest'
        python.version: '3.7'
      Python38Mac:
        imageName: 'macos-latest'
        python.version: '3.8'
      Python39Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.9'
      Python310Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.10'
      Python310Windows:
        imageName: 'windows-latest'
        python.version: '3.10'
      Python310Mac:
        imageName: 'macos-latest'
        python.version: '3.10'
      Python311Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.11'
      Python311Windows:
        imageName: 'windows-latest'
        python.version: '3.11'
      Python311Mac:
        imageName: 'macos-latest'
        python.version: '3.11'
    maxParallel: 4
  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
      allowUnstable: true

  - script: python -m pip install -U pip setuptools
    displayName: 'Update pip'

  - script: pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python setup.py build_ext --inplace -j 2
      python setup.py sdist --formats=gztar
    displayName: 'Compile and build sdist'

  - task: DeleteFiles@1
    inputs:
      contents: 'spacy'
    displayName: 'Delete source directory'

  - script: |
      pip freeze > installed.txt
      pip uninstall -y -r installed.txt
    displayName: 'Uninstall all packages'

  - bash: |
      SDIST=$(python -c "import os;print(os.listdir('./dist')[-1])" 2>&1)
      pip install dist/$SDIST
    displayName: 'Install from sdist'

  - script: |
      pip install -r requirements.txt
      python -m pytest --pyargs spacy
    displayName: 'Run tests'

  - script: |
      python -m spacy download en_core_web_sm
      python -c "import spacy; nlp=spacy.load('en_core_web_sm'); doc=nlp('test')"
    displayName: 'Test download CLI'
    condition: eq(variables['python.version'], '3.9')
